[tool.poetry]
name = "selenium"
version = "0.1.0"
description = ""
authors = ["Alex Rodrigues da Silva <alerodrigues@uolinc.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
